// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ebwaepfmtqxdbqbprhhi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVid2FlcGZtdHF4ZGJxYnByaGhpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY5ODYyODgsImV4cCI6MjA2MjU2MjI4OH0.LqHA7GWYocCERJx0h6SrBodhYlXh1G6OVkTj0PZKWWU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);